use builtin echo -e for zsh prompt

diff --git a/base/.dotfiles-base/lib b/base/.dotfiles-base/lib
--- a/base/.dotfiles-base/lib
+++ b/base/.dotfiles-base/lib
@@ -26,7 +26,7 @@ df_cur_path () {
     local wd="$(basename "$PWD")"
     [ "$wd" = "$USER" ] && wd='~'
     [ "$1" = 'nocolor' ] && df_c_fg_cyan= df_c_reset=
-    echo -e "${df_c_fg_cyan}${wd}${df_c_reset}"
+    printf "${df_c_fg_cyan}${wd}${df_c_reset}"
 }
 
 df_git_dirty () {
@@ -37,17 +37,46 @@ df_git_prompt_info () {
     local cur_branch="$(git branch 2>/dev/null | grep \* | cut -c3-)"
     [ -n "$cur_branch" ] || return
     [ "$1" = 'nocolor' ] && unset df_c_fg_green df_c_reset
-    echo -e " $(df_git_dirty)${df_c_fg_green}${cur_branch}${df_c_reset}"
+    printf " $(df_git_dirty)${df_c_fg_green}${cur_branch}${df_c_reset}"
 }
 
 df_username () {
-    echo -e "${df_c_fg_white_bold}${USER}${df_c_reset}"
+    printf "${df_c_fg_white_bold}${USER}${df_c_reset}"
 }
 
 df_hostname () {
-    echo -e "${df_c_fg_red_bold}$(hostname)${df_c_reset}"
+    printf "${df_c_fg_red_bold}$(hostname)${df_c_reset}"
 }
 
 df_export_PS1 () {
     export PS1='$(df_username)@$(df_hostname) $(df_cur_path)$(df_git_prompt_info) $ '
+}
+
+# zsh PS1 needs to builtin echo -e instead of printf since printf will complain: '%{: invalid directive'
+
+df_cur_path_zsh () {
+    local wd="$(basename "$PWD")"
+    [ "$wd" = "$USER" ] && wd='~'
+    [ "$1" = 'nocolor' ] && df_c_fg_cyan= df_c_reset=
+    builtin echo -e "${df_c_fg_cyan}${wd}${df_c_reset}"
+}
+
+df_git_prompt_info_zsh () {
+    local cur_branch="$(git branch 2>/dev/null | grep \* | cut -c3-)"
+    [ -n "$cur_branch" ] || return
+    [ "$1" = 'nocolor' ] && unset df_c_fg_green df_c_reset
+    builtin echo -e " $(df_git_dirty)${df_c_fg_green}${cur_branch}${df_c_reset}"
+}
+
+df_username_zsh () {
+    builtin echo -e "${df_c_fg_white_bold}${USER}${df_c_reset}"
+}
+
+df_hostname_zsh () {
+    builtin echo -e "${df_c_fg_red_bold}$(hostname)${df_c_reset}"
+}
+
+# zsh-adjusted colors are in .zshrc
+df_export_PS1_zsh () {
+    export PS1='$(df_username_zsh)@$(df_hostname_zsh) $(df_cur_path_zsh)$(df_git_prompt_info_zsh) $ '
 }
