base: adding a basic executable require check to funcs

diff --git a/base/.config/dotfiles/base/functions b/base/.config/dotfiles/base/functions
--- a/base/.config/dotfiles/base/functions
+++ b/base/.config/dotfiles/base/functions
@@ -1,7 +1,7 @@
 # See also: https://github.com/JoshuaRLi/bin
 
 # enforce argc and display usage when violated.
-_usage () {
+usage () {
     if [ "$1" -lt "$2" ]; then
         >&2 cat <<EOF
 ${3}
@@ -16,6 +16,10 @@ die () {
     return 1
 }
 
+require () {
+    df_require "$1" || die "${1} is required, but not found"
+}
+
 
 # man wrapper with --help fallback.
 h () {
@@ -24,28 +28,31 @@ h () {
 
 
 wscan () {
-    _usage $# 1 'uses INTERFACE to scan for wireless AP SSIDs.' \
-        "$0 INTERFACE" || return 1
+    require iw || return $?
+    require awk || return $?
+    require grep || return $?
+    usage $# 1 'uses INTERFACE to scan for wireless AP SSIDs.' \
+        "$0 INTERFACE" || return $?
     sudo iw dev "$1" scan | grep SSID | awk '{print $2}'
 }
 
 
 # print local and external ip.
 myip () {
-    local lip="$(ip route get 1.1.1.1 | awk '{print $(NF-2); exit}')"
-    local eip="$(df_require dig && \
-        dig +short myip.opendns.com @resolver1.opendns.com || \
-         curl -s http://whatismyip.akamai.com)"
+    require ip || return $?
+    require awk || return $?
+    require dig || return $?
     cat <<EOF
-Local: $lip
-External: $eip
+Local: $(ip route get 1.1.1.1 | awk '{print $(NF-2); exit}')
+External: $(dig +short myip.opendns.com @resolver1.opendns.com)
 EOF
 }
 
 
 gitignore () {
-    _usage $# 1 'gitignore.io download wrapper. `gitignore list` to get a types listing.' \
-        "$0 TYPE [TYPE ...]" || return 1
+    require curl || return $?
+    usage $# 1 'gitignore.io download wrapper. `gitignore list` to get a types listing.' \
+        "$0 TYPE [TYPE ...]" || return $?
     if [ "$1" == 'list' ]; then
         curl -sL https://gitignore.io/api/list | tr ',' '\n'
     else
@@ -57,8 +64,9 @@ gitignore () {
 
 
 sshnew () {
-    _usage $# 1 'Generates a secure ssh keypair (openssh format) using ed25519.' \
-        "$0 [keypair name] [optional comment]" || return 1
+    require ssh-keygen || return $?
+    usage $# 1 'Generates a secure ssh keypair (openssh format) using ed25519.' \
+        "$0 [keypair name] [optional comment]" || return $?
     ssh-keygen -o -t ed25519 -a 100 -f "${HOME}/.ssh/${1}" -N '' -C "$2"
     chmod 400 -v "${HOME}/.ssh/${1}"
     chmod 444 -v "${HOME}/.ssh/${1}.pub"
@@ -66,8 +74,9 @@ sshnew () {
 
 
 sshnewrsa () {
-    _usage $# 1 'Generates a secure ssh keypair (openssh format) using rsa-4096.' \
-        "$0 [keypair name] [optional comment]" || return 1
+    require ssh-keygen || return $?
+    usage $# 1 'Generates a secure ssh keypair (openssh format) using rsa-4096.' \
+        "$0 [keypair name] [optional comment]" || return $?
     ssh-keygen -o -t rsa -b 4096 -a 100 -f "${HOME}/.ssh/${1}" -N '' -C "$2"
     chmod 400 -v "${HOME}/.ssh/${1}"
     chmod 444 -v "${HOME}/.ssh/${1}.pub"
@@ -75,14 +84,15 @@ sshnewrsa () {
 
 
 instassh () {
-    _usage $# 4 'Automates ssh keypair generation and installation.' \
-        "$0 [keypair name] [username] [ipv4 addr] [ssh port]" || return 1
+    require ssh-copy-id || return $?
+    usage $# 4 'Automates ssh keypair generation and installation.' \
+        "$0 [keypair name] [username] [ipv4 addr] [ssh port]" || return $?
     (
     set -eu
     sshnew "$1" ''
     printf '\ncopying pubkey...\n'
     ssh-copy-id -i "${HOME}/.ssh/${1}.pub" "${2}@${3}" -p "$4"
-    printf 'writing config stanza...\n'
+    printf 'writing config stanza (also shown below)...\n'
     tee <<EOF >> "${HOME}/.ssh/config"
 
 Host ${1}
