various PS1 fixes and enhancements

diff --git a/base/.config/dotfiles/base/lib b/base/.config/dotfiles/base/lib
--- a/base/.config/dotfiles/base/lib
+++ b/base/.config/dotfiles/base/lib
@@ -1,9 +1,9 @@
 df_warn () {
-    >&2 printf %s\\n "df_warn: ${1}"
+    printf %s\\n "df_warn: ${1}" >&2
 }
 
 df_require () {
-    2>&1 command -v "$1" > /dev/null
+    command -v "$1" 2>&1 > /dev/null
 }
 
 df_c_fg_default=$'\e[39m'
@@ -27,9 +27,7 @@ df_c_fg_white_bold=$'\e[1;97m'
 df_c_reset=$'\e[0m'
 
 df_cur_path () {
-    wd="$(basename "$PWD")"
-    [ "$wd" = "$USER" ] && wd='~'
-    [ "$1" = 'nocolor' ] && df_c_fg_cyan= df_c_reset=
+    [ "$PWD" = "/home/${USER}" ] && wd='~' || wd="${PWD##*/}"
     printf %s "${df_c_fg_cyan}${wd}${df_c_reset}"
 }
 
@@ -38,9 +36,8 @@ df_git_dirty () {
 }
 
 df_git_prompt_info () {
-    cur_branch="$(git branch 2>/dev/null | grep \* | cut -c3-)"
+    cur_branch="$(git branch 2>/dev/null | grep -m1 \* | awk '{print $2; exit}')"
     [ -n "$cur_branch" ] || return
-    [ "$1" = 'nocolor' ] && unset df_c_fg_green df_c_reset
     printf %s " $(df_git_dirty)${df_c_fg_green}${cur_branch}${df_c_reset}"
 }
 
@@ -56,31 +53,30 @@ df_export_PS1 () {
     export PS1='$(df_username)@$(df_hostname) $(df_cur_path)$(df_git_prompt_info) $ '
 }
 
-# zsh PS1 needs to builtin echo -e instead of printf since printf will complain: '%{: invalid directive'
 
-df_cur_path_zsh () {
-    local wd="$(basename "$PWD")"
-    [ "$wd" = "$USER" ] && wd='~'
-    [ "$1" = 'nocolor' ] && df_c_fg_cyan= df_c_reset=
+# zsh PS1 needs echo instead of printf since zsh printf will complain: '%{: invalid directive'
+# mksh doesn't have printf builtin, so echo is preferred
+
+df_cur_path_echo () {
+    [ "$PWD" = "/home/${USER}" ] && wd='~' || wd="${PWD##*/}"
     builtin echo -e "${df_c_fg_cyan}${wd}${df_c_reset}"
 }
 
-df_git_prompt_info_zsh () {
-    local cur_branch="$(git branch 2>/dev/null | grep \* | cut -c3-)"
+df_git_prompt_info_echo () {
+    cur_branch="$(git branch 2>/dev/null | grep -m1 \* | awk '{print $2; exit}')"
     [ -n "$cur_branch" ] || return
-    [ "$1" = 'nocolor' ] && unset df_c_fg_green df_c_reset
     builtin echo -e " $(df_git_dirty)${df_c_fg_green}${cur_branch}${df_c_reset}"
 }
 
-df_username_zsh () {
+df_username_echo () {
     builtin echo -e "${df_c_fg_white_bold}${USER}${df_c_reset}"
 }
 
-df_hostname_zsh () {
+df_hostname_echo () {
     builtin echo -e "${df_c_fg_red_bold}$(hostname)${df_c_reset}"
 }
 
 # zsh-adjusted colors are in .zshrc
-df_export_PS1_zsh () {
-    export PS1='$(df_username_zsh)@$(df_hostname_zsh) $(df_cur_path_zsh)$(df_git_prompt_info_zsh) $ '
+df_export_PS1_echo () {
+    export PS1='$(df_username_echo)@$(df_hostname_echo) $(df_cur_path_echo)$(df_git_prompt_info_echo) $ '
 }
